spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pandora
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: XmutOJ-backend-user-service
          uri: lb://XmutOJ-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: web-file
          uri: lb://web-file
          predicates:
            - Path=/api/file/**
        - id: XmutOJ-backend-question-service
          uri: lb://XmutOJ-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: XmutOJ-backend-judge-service
          uri: lb://XmutOJ-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: web-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
#  servlet:
#    context-path: /api
knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: swagger2
  enable: true
# 这个配置是不用看token是否合法 直接通过
gateway:
  excludedUrls: /api/user/get/login,/api/user/logout,/user/register,/api/user/update/my,/api/user/login,/user/getLoginUser,/api/user/register,/api/question/list/page/vo,/api/file
