spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pandora
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: web-user
          uri: lb://web-user
          predicates:
            - Path=/api/user/**
        - id: web-file
          uri: lb://web-file
          predicates:
            - Path=/api/file/**
        - id: web-code
          uri: lb://web-code
          predicates:
            - Path=/api/questionCode/**
        - id: web-recommend
          uri: lb://web-recommend
          predicates:
            - Path=/api/recommend/**
        - id: web-base
          uri: http://localhost:8109
          predicates:
            - Path=/api/question/**,/api/questionBank/**,/api/mockInterview/**,/api/question_thumb/**,/api/question_favourite/**,/api/question_comment/**,/api/questionBankQuestion/**
        - id: web-post
          uri: lb://web-post
          predicates:
            - Path=/api/post/**,/api/comment/**,/api/post_favour/**,/api/post_thumb/**
#        - id: XmutOJ-backend-judge-service
#          uri: lb://XmutOJ-backend-judge-service
#          predicates:
#            - Path=/api/judge/**
  application:
    name: web-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
